services:
  app1:
    container_name: app1
    image: uv:1
    ports:
      - 8000:8000
    networks:
      - file-net
    depends_on:
      - mariadb
    working_dir: /workspce
    volumes:
      - ./app1/main.py:/workspace/main.py:rw
      - ./app1/db.py:/workspace/db.py:rw
      - ./app1/settings.py:/workspace/settings.py:rw
      - ./app1/pyproject.toml:/workspace/pyproject.toml:ro
      - ./app1/uv.lock:/workspace/uv.lock:ro
      - uploads:/workspace/uploads:rw
    command: ["sleep", "infinity"]

  app2:
    container_name: app2
    image: node:24.13.0
    ports:
      - 80:5173
    networks:
      - file-net
    working_dir: /workspace
    volumes:
      - ./app2/public:/workspace/public:ro
      - ./app2/src:/workspace/src:rw
      - ./app2/eslint.config.js:/workspace/eslint.config.js:ro
      - ./app2/index.html:/workspace/index.html:ro
      - ./app2/package.json:/workspace/package.json:ro
      - ./app2/vite.config.js:/workspace/vite.config.js:ro
    command: ["sleep", "infinity"]

  mariadb:
    container_name: mariadb
    image: mariadb:12.1.2
    restart: always
    ports:
      - 3306:3306
    networks:
      - file-net
    volumes:
      - ./mariadb/conf.d:/etc/mysql/conf.d:ro
      - ./mariadb/initdb.d:/docker-entrypoint-initdb.d:ro
      - mysql:/var/lib/mysql:rw
    environment:
      - MARIADB_HOST=localhost
      - MARIADB_PORT=3306
      - MARIADB_ROOT_PASSWORD=1234
      - MARIADB_DATABASE=edu
      - TZ=Asia/Seoul
      - LC_ALL:en_US.UTF-8

networks:
  file-net:
    driver: bridge

volumes:
  uploads:
  mysql: