apiVersion: v1
kind: ConfigMap

metadata:
  name: app1-config

data:
  APP1_PATH: "/app1"
  APP2_PATH: "/app2"
  APP1_URL: "http://app2-service:8000"
  # 개별 pod의 포트기 때문에 포트가 겹쳐도 됨
  APP2_URL: "http://app3-service:8000"
 